name: simonaapp
description: Final Project Attendance SMM

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^3.2.0
  equatable: ^1.1.1
  meta: ^1.1.8
  dio: ^3.0.9
  sized_context: ^0.2.1+1
  moor: ^2.4.2
  moor_ffi: ^0.4.0
  path: ^1.6.4
  path_provider: ^1.6.5
  google_sign_in: ^4.4.0
  qrscan: ^0.2.17
  firebase_auth: ^0.15.5+3
  flutter_auth_buttons: ^0.8.0
  font_awesome_flutter: ^8.8.1
  cupertino_icons: ^0.1.3
  flutter_socket_io: ^0.6.0
  simple_animations: ^1.3.11
  uuid: ^2.0.4
  flutter_dotenv:

dev_dependencies:
  flutter_test:
    sdk: flutter
  google_fonts: ^0.3.10
  moor_generator: ^2.4.0
  build_runner: ^1.8.1


flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png
    - assets/logo_smm.png
    - .env